### PR TITLE
Native targets in Kotlin Native

### PR DESCRIPTION
**Pull request by shalva97**
Currently thre are few problems with this variant

- I dont know C so there might be errors I missed
- IFileDialog seems to have much easier API, but I was not able to use it
- compose does not support mingwX64 soI made separate module without compose dep
- it has no API which is defined in FilePicker.kt

Maybe you have experience with C?

My idea is that to write native dialogs for all platforms and then JVM variant could depend on those. There will be no need for LWJGL or other weird Java dependency. It will all be pure Kotlin!

### CODE REVIEW

**Comment by Wavesonics** [comment]
Awesome work! I won't have time to work on this till next week, but looking forward to integrating these.

**Comment by shalva97** [comment]
This is taking more time than exepcted cause of lack of documentation. Currently Im exploring https://github.com/whyoleg/ffi-kotlin and https://github.com/cashapp/zipline/tree/trunk/zipline

**Comment by Wavesonics** [comment]
ya know, I think there may be a problem with this approach.

In a given module, you couldn't have a JVM target for instance, that accesses the mingw64 implementation of a function.

so I think we'll need a new module that only implements the file dialog invocations, and it produces per platfrom artifacts. .dll, .a, ect, that then the next module links to at run time I think? And then for JVM targets for instance we'd use JNI to call the functions, and for other targets, not sure how it'd work.

**Comment by shalva97** [comment]
I think we should close this. The are no docs or examples I could learn from. As an alternative I managed to fix existing code and sent a PR https://github.com/Wavesonics/compose-multiplatform-file-picker/pull/24

**Pull request closed without merging**
