### PR TITLE
mingwX64 variant

### PR DESCRIPTION
**Pull request by shalva97**
Currently thre are few problems with this variant
- I dont know C so there might be errors I missed
- IFileDialog seems to have much easier API, but [I was not able to use it ](https://kotlinlang.slack.com/archives/C3PQML5NU/p1683808505136869)
- compose does not support mingwX64 soI made separate module without compose dep
- it has no API which is defined in FilePicker.kt

Maybe you have experience with C?

My idea is that to write native dialogs for all platforms and then JVM variant could depend on those. There will be no need for LWJGL or other weird Java dependency. It will all be pure Kotlin!

### CODE REVIEW

**Comment by Wavesonics** [comment]
I was thinking this as well actually, just writing the native code for each platform that is.

I think this is a good path forward, I'll take a look at this this weekend, thanks for the PR!

**Comment by shalva97** [comment]
Any updates?

**Comment by Wavesonics** [comment]
I can take a look at this tonight

**Comment by Wavesonics** [comment]
@shalva97 can you put this (and future PRs) on its own branch? Makes it hard to test locally on master

**Pull request closed without merging**
