### PR TITLE
Add platform specific FilePicker methods with typed return type

### LINKED ISSUE #69: Why platformFile of MPFile is generic?
When I debug my project in Windows, if found that the type of plaformFile is always the File of java.io. So I wonder if it is necessary to make it generic? Is it possible to have another type of file?

Thankyou

### PR DESCRIPTION
**Pull request by vinceglb**
When using `FilePicker` in platform specific modules like `androidMain` or `iOSMain`, it would be easier to access the typed file directly without needing to check the type of `MPFile.platformFile`.

I suggest here to add a platform specific method for each target, returning `MPFile` with typed `platformFile`.

Example for JVM target:

```kotlin
FilePickerJvm(show, fileExtensions = listOf("jpg", "png")) { file: JvmFile? ->
    if (file != null) {
        // Easy access to java.io.File methods
	println("File chosen: ${file.platformFile.name}")
    }
}
```

Here are the new methods:
- Android: `FilePickerAndroid`
- iOS: `FilePickerIOS`
- JS: `FilePickerWeb`
- JVM: `FilePickerJvm`
- MacOSX64: `FilePickerMacOS`

The method `FilePicker` continues to work everywhere with `MPFile<Any>`.

I updated and tested all examples.

Can fix #69 by adding typed platform MPFile.

### CODE REVIEW

**Comment by shalva97** [comment]
There must be a better way. Adding those functions for all platforms just looks wrong... Also I have never seen such pattern in other libraries which are multiplatform.

 If I add a dependency like `implementation("com.darkrockstudios:mpfilepicker-jvm:3.0.0")` I would expect it to only include JVM dependencies and the received file will have java.io.File type. 
 
I think there is something wrong with the library API. The JVM function type has `FileSelected` which is same as `(MPFile<Any>?) -> Unit`.  I tried to write `(JvmFile?) -> Unit`, which I think is a subtype of `(MPFile<Any>?) -> Unit`, but it did not work...
```
public expect fun FilePicker(
	show: Boolean,
	initialDirectory: String? = null,
	fileExtensions: List<String> = emptyList(),
	title: String? = null,
	onFileSelected: FileSelected, // this should change in JVM
)
```


 Maybe it is possible with subtypes somehow.  I will ask this on Kotlin Slack

**Comment by vinceglb** [comment]
I agree with you. We can provide a better API without adding those functions.

I've updated the PR with an improved solution and less code by introducing an expected class called `PlatformFile`.

Here is an example for Android:

```koltin
FilePicker(showFilePicker) { platformFile ->
   val uri = platformFile?.uri
   // Do something with the uri
}
```

And here for Desktop:

```koltin
FilePicker(showFilePicker) { platformFile ->
   val file = platformFile?.file
   // Do something with the file
}
```

@shalva97 What do you think?

**Comment by shalva97** [comment]
Honestly I think the API is a mess and it is getting worse. There is path, which is just a file name on Web, there is now a title argument, which does not work on all platforms and it is included in all functions....

The best decision for me seems to be to not write common code, but to delete all that we have. There is an idea I have right now to archive this repo, create another library, which will have 0 common code and libraries with different targets will be published as separate libraries

Because there are so many different cases to support I can't imagine all the cases to be covered in common code. My initial idea was that there would be a function that would return a path with a type of String and everyone would be happy. Unfortunately this is not that simple, for example on Web you don't get path of a file, on other platforms it is different objects, same kinds of arguments have different effects on different platforms.

what are your thoughts? @Wavesonics maybe you have some ideas? Im not sure if it is correct way to have common code for all targets

**Comment by shalva97** [comment]
okay, I have asked about this here https://kotlinlang.slack.com/archives/C3PQML5NU/p1703772541744629 let's see what others say.

**Comment by shalva97** [comment]
I have changed my mind once again. The best variant for me seems to have platform specific functions, yes I know I called them ugly, but I don't see a better way.

Could you please revert the latest commits and fix conflicts?

**Comment by vinceglb** [comment]
For me, it is still a good option. 

Here we have the flexibility to:
- Use `FilePicker` in each individual platform source code and easily access to the file of the platform
- Use `FilePicker` in the common source code and handle the returned file with something like this

```kotlin
expect fun handlePlatformFile(platformFile: PlatformFile)

FilePicker(...) { platformFile ->
    handlePlatformFile(platformFile)
}
```

We are in full control of what we want to do on each platform with the file while using `FilePicker` in the common source code, that's great imo.

**Comment by shalva97** [comment]
Agree we do have control of returned type on each platform. Another issue is the arguments, for example `title` argument, which is in common code but does not work on all platforms, so that's why I said that your first solutions was better. Anyways, this is another issue...

okay, I will approve this a bit later, need to run all examples and see if they all work. Also I will create an issue for the argument I mentioned above.

**Pull request merged**
