### PR TITLE
JS target

### PR DESCRIPTION
**Pull request by shalva97**
I have added a new function `suspend fun Document.selectFilesFromDisk`, which creates `HTMLInputElement` in order to trigger the dialog, was researching a lot but could not find anything better.

This was also suggested here: https://kotlinlang.slack.com/archives/C01F2HV7868/p1674571571679729

`main` function does not have run button so to run the JS target use gradle task `browserDevelopmentRun` from the new module

### CODE REVIEW

**Comment by shalva97** [comment]
I got stuck...

So on web, when I select a file I do not have path, but file name and its content, it is a type from `org.w3c.files.File`. For Android and Desktop a path is returned.

my solution now is to have a sealed class, which will return some generic class for all platforms and clients will consume it like

```
when (file) {
   is Web -> doSomethingThatWillHappenForWeb()
   is Android -> file.someAndroidHandlingHere()
}
```

have not added it yet. Do you have ideas? you can take a look at `suspend fun Document.selectFilesFromDisk` to see what is exactly going on...

**Comment by shalva97** [comment]
I have added a sealed interface
```kotlin
sealed interface MPFile {

    // on JS this will be a file name, on other platforms it will be a file path
    val fileNameOrPath: String?

    data class Web(
        override val fileNameOrPath: String,
        private val fileReader: suspend () -> String
    ) : MPFile {
        suspend fun getFileContents() = fileReader()
    }

    data class Other(override val fileNameOrPath: String?) : MPFile
}
```

in the last few commits it is all working. If you run `browserDevelopmentRun` it will open browser with the website. There will be one button by which it is possible to trigger File Chooser, pick a file and see it's file name and contents

**Comment by shalva97** [comment]
Also had to change the API a lot, actually I need to change it more... :D

The thing is that on web it is also possible to specify if user can pick one or multiple files.

so Im going to add something like

```kotlin
@Composable
expect fun FilePicker(
    show: Boolean,
    initialDirectory: String? = null,
    fileExtensions: List<String> = emptyList(),
    isMultiple: Boolean, // new argument here
    onFileSelected: (MPFile?) -> Unit // new MPFile type here
)
```

Right now I need some directions. Is what I am doing acceptable? Need feedback...

**Comment by Wavesonics** [comment]
hey @shalva97 I'll take a look at this this weekend

**Comment by shalva97** [comment]
Hello, any updates here?

**Comment by Wavesonics** [comment]
@shalva97 Hey ya I made some changes on top of yours and opened a PR to your fork: https://github.com/shalva97/compose-multiplatform-file-picker/pull/1

Pull them in and update this branch if you're happy with them, and I'll merge it.

**Pull request merged**
